export interface Beat {
  id: string
  title: string
  artist: string
  price: string
  bpm: number
  musicalKey?: string
  genres: string[]
  tags: string[]
  typeBeat?: string
  mood?: string[]
  image: string
  audioUrl: string
  isFree: boolean
}

export const beatsData: Beat[] = [
  // Kanye West Type Beats
  {
    id: "beat-kanye-1",
    title: "Kanye West Type Beat - Graduation Vibes",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 104,
    musicalKey: "C Major",
    genres: ["Hip Hop", "Pop Rap"],
    tags: ["kanye west", "uplifting", "synth", "graduation"],
    typeBeat: "Kanye West",
    mood: ["Uplifting", "Energetic", "Happy"],
    image: "/kanye-graduation.jpg",
    audioUrl: "/audio/kanye-graduation.mp3",
    isFree: false,
  },
  {
    id: "beat-kanye-2",
    title: "Kanye West Type Beat - 808s & Heartbreak",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 120,
    musicalKey: "A Minor",
    genres: ["Hip Hop", "R&B", "Alternative"],
    tags: ["kanye west", "emotional", "808s", "heartbreak", "autotune"],
    typeBeat: "Kanye West",
    mood: ["Sad", "Emotional", "Dark"],
    image: "/kanye-808s.jpg",
    audioUrl: "/audio/kanye-808s.mp3",
    isFree: false,
  },
  {
    id: "beat-kanye-3",
    title: "Kanye West Type Beat - Yeezus Energy",
    artist: "FЯEEZY",
    price: "$55.00",
    bpm: 140,
    musicalKey: "E Minor",
    genres: ["Experimental", "Hip Hop", "Industrial"],
    tags: ["kanye west", "aggressive", "industrial", "experimental", "hard"],
    typeBeat: "Kanye West",
    mood: ["Aggressive", "Dark", "Energetic"],
    image: "/kanye-yeezus.jpg",
    audioUrl: "/audio/kanye-yeezus.mp3",
    isFree: false,
  },
  {
    id: "beat-kanye-4",
    title: "Kanye West Type Beat - College Dropout",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 95,
    musicalKey: "G Major",
    genres: ["Hip Hop", "Soul"],
    tags: ["kanye west", "soulful", "chipmunk soul", "classic", "sample"],
    typeBeat: "Kanye West",
    mood: ["Chill", "Happy", "Nostalgic"],
    image: "/kanye-college.jpg",
    audioUrl: "/audio/kanye-college.mp3",
    isFree: true,
  },
  {
    id: "beat-kanye-5",
    title: "Kanye West Type Beat - Donda Gospel",
    artist: "FЯEEZY",
    price: "$48.00",
    bpm: 130,
    musicalKey: "D Major",
    genres: ["Hip Hop", "Gospel", "Trap"],
    tags: ["kanye west", "gospel", "choir", "spiritual", "donda"],
    typeBeat: "Kanye West",
    mood: ["Uplifting", "Spiritual", "Energetic"],
    image: "/kanye-donda.jpg",
    audioUrl: "/audio/kanye-donda.mp3",
    isFree: false,
  },

  // Drake Type Beats
  {
    id: "beat-drake-1",
    title: "Drake Type Beat - Champagne Poetry",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 102,
    musicalKey: "F# Minor",
    genres: ["Hip Hop", "R&B"],
    tags: ["drake", "smooth", "classy", "melodic"],
    typeBeat: "Drake",
    mood: ["Chill", "Smooth", "Confident"],
    image: "/champagne-luxury.jpg",
    audioUrl: "/audio/drake-champagne.mp3",
    isFree: false,
  },
  {
    id: "beat-drake-2",
    title: "Drake Type Beat - Views From The 6",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 135,
    musicalKey: "C Minor",
    genres: ["Hip Hop", "R&B", "Trap"],
    tags: ["drake", "atmospheric", "toronto", "ovo"],
    typeBeat: "Drake",
    mood: ["Dark", "Atmospheric", "Emotional"],
    image: "/drake-views.jpg",
    audioUrl: "/audio/drake-views.mp3",
    isFree: false,
  },
  {
    id: "beat-drake-3",
    title: "Drake Type Beat - Nothing Was The Same",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 88,
    musicalKey: "A Minor",
    genres: ["Hip Hop", "R&B"],
    tags: ["drake", "emotional", "piano", "melodic"],
    typeBeat: "Drake",
    mood: ["Sad", "Emotional", "Reflective"],
    image: "/drake-nwts.jpg",
    audioUrl: "/audio/drake-nwts.mp3",
    isFree: true,
  },

  // Travis Scott Type Beats
  {
    id: "beat-travis-1",
    title: "Travis Scott Type Beat - Astroworld Vibes",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 145,
    musicalKey: "B Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["travis scott", "psychedelic", "hard", "astroworld"],
    typeBeat: "Travis Scott",
    mood: ["Energetic", "Dark", "Psychedelic"],
    image: "/astroworld-space.jpg",
    audioUrl: "/audio/travis-astro.mp3",
    isFree: false,
  },
  {
    id: "beat-travis-2",
    title: "Travis Scott Type Beat - Rodeo",
    artist: "FЯEEZY",
    price: "$48.00",
    bpm: 140,
    musicalKey: "G Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["travis scott", "rage", "hard", "808"],
    typeBeat: "Travis Scott",
    mood: ["Aggressive", "Energetic", "Dark"],
    image: "/travis-rodeo.jpg",
    audioUrl: "/audio/travis-rodeo.mp3",
    isFree: false,
  },

  // Lil Baby Type Beats
  {
    id: "beat-lilbaby-1",
    title: "Lil Baby Type Beat - Street Gossip",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 150,
    musicalKey: "D Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["lil baby", "melodic trap", "street", "atlanta"],
    typeBeat: "Lil Baby",
    mood: ["Energetic", "Confident", "Street"],
    image: "/lilbaby-street.jpg",
    audioUrl: "/audio/lilbaby-street.mp3",
    isFree: false,
  },
  {
    id: "beat-lilbaby-2",
    title: "Lil Baby Type Beat - My Turn",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 155,
    musicalKey: "F Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["lil baby", "hard", "melodic", "piano"],
    typeBeat: "Lil Baby",
    mood: ["Aggressive", "Confident", "Energetic"],
    image: "/lilbaby-myturn.jpg",
    audioUrl: "/audio/lilbaby-myturn.mp3",
    isFree: false,
  },

  // Gunna Type Beats
  {
    id: "beat-gunna-1",
    title: "Gunna Type Beat - Drip Season",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 142,
    musicalKey: "E Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["gunna", "melodic", "drip", "smooth"],
    typeBeat: "Gunna",
    mood: ["Chill", "Smooth", "Confident"],
    image: "/gunna-drip.jpg",
    audioUrl: "/audio/gunna-drip.mp3",
    isFree: false,
  },

  // Future Type Beats
  {
    id: "beat-future-1",
    title: "Future Type Beat - DS2",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 138,
    musicalKey: "C# Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["future", "dark", "hard", "808"],
    typeBeat: "Future",
    mood: ["Dark", "Aggressive", "Energetic"],
    image: "/future-ds2.jpg",
    audioUrl: "/audio/future-ds2.mp3",
    isFree: false,
  },

  // The Weeknd Type Beats
  {
    id: "beat-weeknd-1",
    title: "The Weeknd Type Beat - After Hours",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 118,
    musicalKey: "A Minor",
    genres: ["R&B", "Pop", "Alternative"],
    tags: ["the weeknd", "dark rnb", "synth", "atmospheric"],
    typeBeat: "The Weeknd",
    mood: ["Dark", "Emotional", "Atmospheric"],
    image: "/weeknd-afterhours.jpg",
    audioUrl: "/audio/weeknd-afterhours.mp3",
    isFree: false,
  },
  {
    id: "beat-weeknd-2",
    title: "The Weeknd Type Beat - Starboy",
    artist: "FЯEEZY",
    price: "$48.00",
    bpm: 106,
    musicalKey: "F Minor",
    genres: ["R&B", "Pop"],
    tags: ["the weeknd", "synth pop", "upbeat", "catchy"],
    typeBeat: "The Weeknd",
    mood: ["Uplifting", "Energetic", "Confident"],
    image: "/weeknd-starboy.jpg",
    audioUrl: "/audio/weeknd-starboy.mp3",
    isFree: false,
  },

  // Bryson Tiller Type Beats
  {
    id: "beat-bryson-1",
    title: "Bryson Tiller Type Beat - Trapsoul",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 140,
    musicalKey: "G Minor",
    genres: ["R&B", "Trap"],
    tags: ["bryson tiller", "trapsoul", "melodic", "smooth"],
    typeBeat: "Bryson Tiller",
    mood: ["Chill", "Smooth", "Romantic"],
    image: "/bryson-trapsoul.jpg",
    audioUrl: "/audio/bryson-trapsoul.mp3",
    isFree: false,
  },

  // J. Cole Type Beats
  {
    id: "beat-jcole-1",
    title: "J. Cole Type Beat - Forest Hills Drive",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 92,
    musicalKey: "D Major",
    genres: ["Hip Hop", "Conscious Rap"],
    tags: ["j cole", "soulful", "storytelling", "sample"],
    typeBeat: "J. Cole",
    mood: ["Reflective", "Chill", "Nostalgic"],
    image: "/jcole-fhd.jpg",
    audioUrl: "/audio/jcole-fhd.mp3",
    isFree: false,
  },

  // Kendrick Lamar Type Beats
  {
    id: "beat-kendrick-1",
    title: "Kendrick Lamar Type Beat - DAMN.",
    artist: "FЯEEZY",
    price: "$55.00",
    bpm: 150,
    musicalKey: "B Minor",
    genres: ["Hip Hop", "Conscious Rap"],
    tags: ["kendrick lamar", "hard", "complex", "lyrical"],
    typeBeat: "Kendrick Lamar",
    mood: ["Aggressive", "Energetic", "Intense"],
    image: "/kendrick-damn.jpg",
    audioUrl: "/audio/kendrick-damn.mp3",
    isFree: false,
  },
  {
    id: "beat-kendrick-2",
    title: "Kendrick Lamar Type Beat - Good Kid",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 98,
    musicalKey: "F# Minor",
    genres: ["Hip Hop", "West Coast"],
    tags: ["kendrick lamar", "west coast", "storytelling", "smooth"],
    typeBeat: "Kendrick Lamar",
    mood: ["Chill", "Reflective", "Nostalgic"],
    image: "/kendrick-gkmc.jpg",
    audioUrl: "/audio/kendrick-gkmc.mp3",
    isFree: true,
  },

  // Playboi Carti Type Beats
  {
    id: "beat-carti-1",
    title: "Playboi Carti Type Beat - Whole Lotta Red",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 140,
    musicalKey: "E Minor",
    genres: ["Trap", "Experimental"],
    tags: ["playboi carti", "rage", "punk", "experimental"],
    typeBeat: "Playboi Carti",
    mood: ["Aggressive", "Energetic", "Chaotic"],
    image: "/carti-wlr.jpg",
    audioUrl: "/audio/carti-wlr.mp3",
    isFree: false,
  },

  // Lil Uzi Vert Type Beats
  {
    id: "beat-uzi-1",
    title: "Lil Uzi Vert Type Beat - Eternal Atake",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 160,
    musicalKey: "C# Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["lil uzi vert", "melodic", "fast", "spacey"],
    typeBeat: "Lil Uzi Vert",
    mood: ["Energetic", "Uplifting", "Psychedelic"],
    image: "/uzi-ea.jpg",
    audioUrl: "/audio/uzi-ea.mp3",
    isFree: false,
  },

  // Juice WRLD Type Beats
  {
    id: "beat-juice-1",
    title: "Juice WRLD Type Beat - Legends Never Die",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 140,
    musicalKey: "A Minor",
    genres: ["Hip Hop", "Emo Rap"],
    tags: ["juice wrld", "emotional", "guitar", "melodic"],
    typeBeat: "Juice WRLD",
    mood: ["Sad", "Emotional", "Melodic"],
    image: "/juice-lnd.jpg",
    audioUrl: "/audio/juice-lnd.mp3",
    isFree: false,
  },
  {
    id: "beat-juice-2",
    title: "Juice WRLD Type Beat - Goodbye & Good Riddance",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 150,
    musicalKey: "D Minor",
    genres: ["Hip Hop", "Emo Rap"],
    tags: ["juice wrld", "heartbreak", "melodic", "808"],
    typeBeat: "Juice WRLD",
    mood: ["Sad", "Emotional", "Energetic"],
    image: "/juice-ggr.jpg",
    audioUrl: "/audio/juice-ggr.mp3",
    isFree: true,
  },

  // Post Malone Type Beats
  {
    id: "beat-post-1",
    title: "Post Malone Type Beat - Hollywood's Bleeding",
    artist: "FЯEEZY",
    price: "$48.00",
    bpm: 145,
    musicalKey: "G Major",
    genres: ["Pop", "Hip Hop", "Rock"],
    tags: ["post malone", "guitar", "melodic", "catchy"],
    typeBeat: "Post Malone",
    mood: ["Uplifting", "Melodic", "Catchy"],
    image: "/post-hb.jpg",
    audioUrl: "/audio/post-hb.mp3",
    isFree: false,
  },

  // 21 Savage Type Beats
  {
    id: "beat-21savage-1",
    title: "21 Savage Type Beat - Savage Mode",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 135,
    musicalKey: "F Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["21 savage", "dark", "hard", "metro boomin"],
    typeBeat: "21 Savage",
    mood: ["Dark", "Aggressive", "Street"],
    image: "/21savage-sm.jpg",
    audioUrl: "/audio/21savage-sm.mp3",
    isFree: false,
  },

  // Lil Durk Type Beats
  {
    id: "beat-durk-1",
    title: "Lil Durk Type Beat - The Voice",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 156,
    musicalKey: "C Minor",
    genres: ["Trap", "Hip Hop", "Drill"],
    tags: ["lil durk", "melodic", "emotional", "chicago"],
    typeBeat: "Lil Durk",
    mood: ["Emotional", "Energetic", "Street"],
    image: "/durk-voice.jpg",
    audioUrl: "/audio/durk-voice.mp3",
    isFree: false,
  },

  // Rod Wave Type Beats
  {
    id: "beat-rodwave-1",
    title: "Rod Wave Type Beat - SoulFly",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 140,
    musicalKey: "E Minor",
    genres: ["Hip Hop", "R&B", "Soul"],
    tags: ["rod wave", "emotional", "piano", "soulful"],
    typeBeat: "Rod Wave",
    mood: ["Sad", "Emotional", "Soulful"],
    image: "/rodwave-soulfly.jpg",
    audioUrl: "/audio/rodwave-soulfly.mp3",
    isFree: false,
  },

  // Polo G Type Beats
  {
    id: "beat-polog-1",
    title: "Polo G Type Beat - Hall of Fame",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 145,
    musicalKey: "A Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["polo g", "melodic", "piano", "chicago"],
    typeBeat: "Polo G",
    mood: ["Energetic", "Melodic", "Confident"],
    image: "/polog-hof.jpg",
    audioUrl: "/audio/polog-hof.mp3",
    isFree: false,
  },

  // NBA YoungBoy Type Beats
  {
    id: "beat-nba-1",
    title: "NBA YoungBoy Type Beat - Top",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 150,
    musicalKey: "D Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["nba youngboy", "melodic", "aggressive", "louisiana"],
    typeBeat: "NBA YoungBoy",
    mood: ["Aggressive", "Energetic", "Emotional"],
    image: "/nba-top.jpg",
    audioUrl: "/audio/nba-top.mp3",
    isFree: false,
  },

  // Central Cee Type Beats
  {
    id: "beat-centralcee-1",
    title: "Central Cee Type Beat - 23",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 140,
    musicalKey: "G Minor",
    genres: ["Drill", "UK Rap"],
    tags: ["central cee", "uk drill", "melodic", "london"],
    typeBeat: "Central Cee",
    mood: ["Dark", "Melodic", "Street"],
    image: "/centralcee-23.jpg",
    audioUrl: "/audio/centralcee-23.mp3",
    isFree: false,
  },

  // Dave Type Beats
  {
    id: "beat-dave-1",
    title: "Dave Type Beat - Psychodrama",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 138,
    musicalKey: "F# Minor",
    genres: ["UK Rap", "Hip Hop"],
    tags: ["dave", "uk rap", "storytelling", "piano"],
    typeBeat: "Dave",
    mood: ["Reflective", "Emotional", "Dark"],
    image: "/dave-psycho.jpg",
    audioUrl: "/audio/dave-psycho.mp3",
    isFree: false,
  },

  // Pop Smoke Type Beats
  {
    id: "beat-popsmoke-1",
    title: "Pop Smoke Type Beat - Shoot For The Stars",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 140,
    musicalKey: "C Minor",
    genres: ["Drill", "Hip Hop"],
    tags: ["pop smoke", "brooklyn drill", "hard", "808"],
    typeBeat: "Pop Smoke",
    mood: ["Aggressive", "Dark", "Energetic"],
    image: "/popsmoke-sfts.jpg",
    audioUrl: "/audio/popsmoke-sfts.mp3",
    isFree: false,
  },

  // Burna Boy Type Beats
  {
    id: "beat-burna-1",
    title: "Burna Boy Type Beat - African Giant",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 112,
    musicalKey: "E Major",
    genres: ["Afrobeat", "Dancehall"],
    tags: ["burna boy", "afrobeat", "dancehall", "african"],
    typeBeat: "Burna Boy",
    mood: ["Uplifting", "Energetic", "Happy"],
    image: "/afrobeat-colorful.jpg",
    audioUrl: "/audio/burna-ag.mp3",
    isFree: false,
  },

  // Wizkid Type Beats
  {
    id: "beat-wizkid-1",
    title: "Wizkid Type Beat - Made In Lagos",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 105,
    musicalKey: "A Major",
    genres: ["Afrobeat", "R&B"],
    tags: ["wizkid", "afrobeat", "smooth", "lagos"],
    typeBeat: "Wizkid",
    mood: ["Chill", "Smooth", "Happy"],
    image: "/wizkid-mil.jpg",
    audioUrl: "/audio/wizkid-mil.mp3",
    isFree: false,
  },

  // Bad Bunny Type Beats
  {
    id: "beat-badbunny-1",
    title: "Bad Bunny Type Beat - Un Verano Sin Ti",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 98,
    musicalKey: "D Major",
    genres: ["Reggaeton", "Latin Trap"],
    tags: ["bad bunny", "reggaeton", "latin", "summer"],
    typeBeat: "Bad Bunny",
    mood: ["Uplifting", "Happy", "Party"],
    image: "/badbunny-uvst.jpg",
    audioUrl: "/audio/badbunny-uvst.mp3",
    isFree: false,
  },

  // Tyler, The Creator Type Beats
  {
    id: "beat-tyler-1",
    title: "Tyler, The Creator Type Beat - IGOR",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 128,
    musicalKey: "F Major",
    genres: ["Alternative Hip Hop", "Neo-Soul"],
    tags: ["tyler the creator", "experimental", "synth", "unique"],
    typeBeat: "Tyler, The Creator",
    mood: ["Psychedelic", "Emotional", "Creative"],
    image: "/tyler-igor.jpg",
    audioUrl: "/audio/tyler-igor.mp3",
    isFree: false,
  },

  // Frank Ocean Type Beats
  {
    id: "beat-frank-1",
    title: "Frank Ocean Type Beat - Blonde",
    artist: "FЯEEZY",
    price: "$55.00",
    bpm: 110,
    musicalKey: "E Major",
    genres: ["R&B", "Alternative"],
    tags: ["frank ocean", "ambient", "emotional", "artistic"],
    typeBeat: "Frank Ocean",
    mood: ["Chill", "Emotional", "Atmospheric"],
    image: "/frank-blonde.jpg",
    audioUrl: "/audio/frank-blonde.mp3",
    isFree: false,
  },

  // SZA Type Beats
  {
    id: "beat-sza-1",
    title: "SZA Type Beat - SOS",
    artist: "FЯEEZY",
    price: "$48.00",
    bpm: 125,
    musicalKey: "G Major",
    genres: ["R&B", "Alternative R&B"],
    tags: ["sza", "rnb", "melodic", "emotional"],
    typeBeat: "SZA",
    mood: ["Emotional", "Smooth", "Confident"],
    image: "/sza-sos.jpg",
    audioUrl: "/audio/sza-sos.mp3",
    isFree: false,
  },

  // Metro Boomin Type Beats
  {
    id: "beat-metro-1",
    title: "Metro Boomin Type Beat - Heroes & Villains",
    artist: "FЯEEZY",
    price: "$52.00",
    bpm: 140,
    musicalKey: "C# Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["metro boomin", "dark", "hard", "808"],
    typeBeat: "Metro Boomin",
    mood: ["Dark", "Aggressive", "Cinematic"],
    image: "/metro-hv.jpg",
    audioUrl: "/audio/metro-hv.mp3",
    isFree: false,
  },

  // Lil Tecca Type Beats
  {
    id: "beat-tecca-1",
    title: "Lil Tecca Type Beat - Virgo World",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 155,
    musicalKey: "B Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["lil tecca", "melodic", "upbeat", "catchy"],
    typeBeat: "Lil Tecca",
    mood: ["Uplifting", "Energetic", "Melodic"],
    image: "/tecca-vw.jpg",
    audioUrl: "/audio/tecca-vw.mp3",
    isFree: false,
  },

  // Trippie Redd Type Beats
  {
    id: "beat-trippie-1",
    title: "Trippie Redd Type Beat - Life's A Trip",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 145,
    musicalKey: "A Minor",
    genres: ["Hip Hop", "Emo Rap"],
    tags: ["trippie redd", "melodic", "rock", "emotional"],
    typeBeat: "Trippie Redd",
    mood: ["Energetic", "Emotional", "Melodic"],
    image: "/trippie-lat.jpg",
    audioUrl: "/audio/trippie-lat.mp3",
    isFree: false,
  },

  // Lil Peep Type Beats
  {
    id: "beat-peep-1",
    title: "Lil Peep Type Beat - Come Over When You're Sober",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 130,
    musicalKey: "E Minor",
    genres: ["Emo Rap", "Alternative"],
    tags: ["lil peep", "emo", "guitar", "sad"],
    typeBeat: "Lil Peep",
    mood: ["Sad", "Emotional", "Dark"],
    image: "/peep-cowys.jpg",
    audioUrl: "/audio/peep-cowys.mp3",
    isFree: false,
  },

  // XXXTentacion Type Beats
  {
    id: "beat-xxx-1",
    title: "XXXTentacion Type Beat - ?",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 140,
    musicalKey: "D Minor",
    genres: ["Hip Hop", "Alternative"],
    tags: ["xxxtentacion", "emotional", "versatile", "dark"],
    typeBeat: "XXXTentacion",
    mood: ["Sad", "Aggressive", "Emotional"],
    image: "/xxx-question.jpg",
    audioUrl: "/audio/xxx-question.mp3",
    isFree: false,
  },

  // Ski Mask The Slump God Type Beats
  {
    id: "beat-ski-1",
    title: "Ski Mask The Slump God Type Beat - Stokeley",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 160,
    musicalKey: "F# Minor",
    genres: ["Hip Hop", "Trap"],
    tags: ["ski mask", "fast", "energetic", "hard"],
    typeBeat: "Ski Mask The Slump God",
    mood: ["Energetic", "Aggressive", "Chaotic"],
    image: "/ski-stokeley.jpg",
    audioUrl: "/audio/ski-stokeley.mp3",
    isFree: false,
  },

  // Denzel Curry Type Beats
  {
    id: "beat-denzel-1",
    title: "Denzel Curry Type Beat - TA13OO",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 150,
    musicalKey: "G Minor",
    genres: ["Hip Hop", "Experimental"],
    tags: ["denzel curry", "aggressive", "hard", "experimental"],
    typeBeat: "Denzel Curry",
    mood: ["Aggressive", "Dark", "Energetic"],
    image: "/denzel-taboo.jpg",
    audioUrl: "/audio/denzel-taboo.mp3",
    isFree: false,
  },

  // JID Type Beats
  {
    id: "beat-jid-1",
    title: "JID Type Beat - The Never Story",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 142,
    musicalKey: "C Minor",
    genres: ["Hip Hop", "Conscious Rap"],
    tags: ["jid", "lyrical", "complex", "atlanta"],
    typeBeat: "JID",
    mood: ["Energetic", "Confident", "Complex"],
    image: "/jid-tns.jpg",
    audioUrl: "/audio/jid-tns.mp3",
    isFree: false,
  },

  // Cordae Type Beats
  {
    id: "beat-cordae-1",
    title: "Cordae Type Beat - The Lost Boy",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 95,
    musicalKey: "D Major",
    genres: ["Hip Hop", "Conscious Rap"],
    tags: ["cordae", "lyrical", "soulful", "boom bap"],
    typeBeat: "Cordae",
    mood: ["Chill", "Reflective", "Confident"],
    image: "/cordae-tlb.jpg",
    audioUrl: "/audio/cordae-tlb.mp3",
    isFree: false,
  },

  // DaBaby Type Beats
  {
    id: "beat-dababy-1",
    title: "DaBaby Type Beat - Kirk",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 148,
    musicalKey: "E Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["dababy", "bouncy", "energetic", "hard"],
    typeBeat: "DaBaby",
    mood: ["Energetic", "Chaotic", "Aggressive"],
    image: "/dababy-kirk.jpg",
    audioUrl: "/audio/dababy-kirk.mp3",
    isFree: false,
  },

  // Roddy Ricch Type Beats
  {
    id: "beat-roddy-1",
    title: "Roddy Ricch Type Beat - Please Excuse Me",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 140,
    musicalKey: "A Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["roddy ricch", "melodic", "west coast", "smooth"],
    typeBeat: "Roddy Ricch",
    mood: ["Melodic", "Smooth", "Confident"],
    image: "/roddy-pem.jpg",
    audioUrl: "/audio/roddy-pem.mp3",
    isFree: false,
  },

  // Migos Type Beats
  {
    id: "beat-migos-1",
    title: "Migos Type Beat - Culture",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 145,
    musicalKey: "C# Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["migos", "triplet flow", "atlanta", "hard"],
    typeBeat: "Migos",
    mood: ["Energetic", "Party", "Confident"],
    image: "/migos-culture.jpg",
    audioUrl: "/audio/migos-culture.mp3",
    isFree: false,
  },

  // Offset Type Beats
  {
    id: "beat-offset-1",
    title: "Offset Type Beat - Father of 4",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 140,
    musicalKey: "F Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["offset", "melodic trap", "atlanta", "hard"],
    typeBeat: "Offset",
    mood: ["Aggressive", "Melodic", "Confident"],
    image: "/offset-fo4.jpg",
    audioUrl: "/audio/offset-fo4.mp3",
    isFree: false,
  },

  // Quavo Type Beats
  {
    id: "beat-quavo-1",
    title: "Quavo Type Beat - Quavo Huncho",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 150,
    musicalKey: "G Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["quavo", "melodic", "catchy", "atlanta"],
    typeBeat: "Quavo",
    mood: ["Uplifting", "Energetic", "Party"],
    image: "/quavo-qh.jpg",
    audioUrl: "/audio/quavo-qh.mp3",
    isFree: false,
  },

  // Young Thug Type Beats
  {
    id: "beat-thug-1",
    title: "Young Thug Type Beat - So Much Fun",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 138,
    musicalKey: "D Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["young thug", "melodic", "unique", "atlanta"],
    typeBeat: "Young Thug",
    mood: ["Energetic", "Creative", "Melodic"],
    image: "/thug-smf.jpg",
    audioUrl: "/audio/thug-smf.mp3",
    isFree: false,
  },

  // Lil Wayne Type Beats
  {
    id: "beat-wayne-1",
    title: "Lil Wayne Type Beat - Tha Carter V",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 135,
    musicalKey: "E Minor",
    genres: ["Hip Hop", "Trap"],
    tags: ["lil wayne", "classic", "hard", "new orleans"],
    typeBeat: "Lil Wayne",
    mood: ["Confident", "Aggressive", "Energetic"],
    image: "/wayne-cv.jpg",
    audioUrl: "/audio/wayne-cv.mp3",
    isFree: false,
  },

  // A$AP Rocky Type Beats
  {
    id: "beat-rocky-1",
    title: "A$AP Rocky Type Beat - Testing",
    artist: "FЯEEZY",
    price: "$48.00",
    bpm: 130,
    musicalKey: "F# Minor",
    genres: ["Hip Hop", "Experimental"],
    tags: ["asap rocky", "experimental", "psychedelic", "fashion"],
    typeBeat: "A$AP Rocky",
    mood: ["Psychedelic", "Confident", "Creative"],
    image: "/rocky-testing.jpg",
    audioUrl: "/audio/rocky-testing.mp3",
    isFree: false,
  },

  // Mac Miller Type Beats
  {
    id: "beat-mac-1",
    title: "Mac Miller Type Beat - Swimming",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 115,
    musicalKey: "G Major",
    genres: ["Hip Hop", "Alternative"],
    tags: ["mac miller", "jazzy", "soulful", "emotional"],
    typeBeat: "Mac Miller",
    mood: ["Chill", "Emotional", "Reflective"],
    image: "/mac-swimming.jpg",
    audioUrl: "/audio/mac-swimming.mp3",
    isFree: false,
  },

  // Kid Cudi Type Beats
  {
    id: "beat-cudi-1",
    title: "Kid Cudi Type Beat - Man on the Moon",
    artist: "FЯEEZY",
    price: "$50.00",
    bpm: 125,
    musicalKey: "A Minor",
    genres: ["Hip Hop", "Alternative"],
    tags: ["kid cudi", "spacey", "emotional", "atmospheric"],
    typeBeat: "Kid Cudi",
    mood: ["Atmospheric", "Emotional", "Psychedelic"],
    image: "/cudi-motm.jpg",
    audioUrl: "/audio/cudi-motm.mp3",
    isFree: false,
  },

  // Don Toliver Type Beats
  {
    id: "beat-don-1",
    title: "Don Toliver Type Beat - Heaven or Hell",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 140,
    musicalKey: "C Minor",
    genres: ["Hip Hop", "R&B", "Trap"],
    tags: ["don toliver", "melodic", "autotune", "cactus jack"],
    typeBeat: "Don Toliver",
    mood: ["Melodic", "Smooth", "Energetic"],
    image: "/don-hoh.jpg",
    audioUrl: "/audio/don-hoh.mp3",
    isFree: false,
  },

  // Sheck Wes Type Beats
  {
    id: "beat-sheck-1",
    title: "Sheck Wes Type Beat - Mudboy",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 150,
    musicalKey: "E Minor",
    genres: ["Trap", "Hip Hop"],
    tags: ["sheck wes", "hard", "aggressive", "cactus jack"],
    typeBeat: "Sheck Wes",
    mood: ["Aggressive", "Energetic", "Raw"],
    image: "/sheck-mudboy.jpg",
    audioUrl: "/audio/sheck-mudboy.mp3",
    isFree: false,
  },

  // Yeat Type Beats
  {
    id: "beat-yeat-1",
    title: "Yeat Type Beat - 2 Alive",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 155,
    musicalKey: "D Minor",
    genres: ["Trap", "Rage"],
    tags: ["yeat", "rage", "bell", "hyperpop"],
    typeBeat: "Yeat",
    mood: ["Energetic", "Aggressive", "Chaotic"],
    image: "/yeat-2alive.jpg",
    audioUrl: "/audio/yeat-2alive.mp3",
    isFree: false,
  },

  // Ken Carson Type Beats
  {
    id: "beat-ken-1",
    title: "Ken Carson Type Beat - X",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 140,
    musicalKey: "F Minor",
    genres: ["Trap", "Rage"],
    tags: ["ken carson", "rage", "opium", "experimental"],
    typeBeat: "Ken Carson",
    mood: ["Aggressive", "Energetic", "Dark"],
    image: "/ken-x.jpg",
    audioUrl: "/audio/ken-x.mp3",
    isFree: false,
  },

  // Destroy Lonely Type Beats
  {
    id: "beat-lonely-1",
    title: "Destroy Lonely Type Beat - No Stylist",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 145,
    musicalKey: "G Minor",
    genres: ["Trap", "Rage"],
    tags: ["destroy lonely", "rage", "opium", "dark"],
    typeBeat: "Destroy Lonely",
    mood: ["Dark", "Energetic", "Atmospheric"],
    image: "/lonely-ns.jpg",
    audioUrl: "/audio/lonely-ns.mp3",
    isFree: false,
  },

  // Homixide Gang Type Beats
  {
    id: "beat-homixide-1",
    title: "Homixide Gang Type Beat - Snot or Not",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 150,
    musicalKey: "C# Minor",
    genres: ["Trap", "Rage"],
    tags: ["homixide gang", "rage", "opium", "aggressive"],
    typeBeat: "Homixide Gang",
    mood: ["Aggressive", "Dark", "Chaotic"],
    image: "/homixide-son.jpg",
    audioUrl: "/audio/homixide-son.mp3",
    isFree: false,
  },

  // Lancey Foux Type Beats
  {
    id: "beat-lancey-1",
    title: "Lancey Foux Type Beat - Friend or Foux",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 138,
    musicalKey: "A Minor",
    genres: ["Trap", "UK Rap"],
    tags: ["lancey foux", "uk", "experimental", "opium"],
    typeBeat: "Lancey Foux",
    mood: ["Dark", "Creative", "Atmospheric"],
    image: "/lancey-fof.jpg",
    audioUrl: "/audio/lancey-fof.mp3",
    isFree: false,
  },

  // Summrs Type Beats
  {
    id: "beat-summrs-1",
    title: "Summrs Type Beat - Devotion",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 145,
    musicalKey: "E Minor",
    genres: ["Trap", "Plugg"],
    tags: ["summrs", "plugg", "melodic", "underground"],
    typeBeat: "Summrs",
    mood: ["Melodic", "Chill", "Atmospheric"],
    image: "/summrs-devotion.jpg",
    audioUrl: "/audio/summrs-devotion.mp3",
    isFree: false,
  },

  // Kankan Type Beats
  {
    id: "beat-kankan-1",
    title: "Kankan Type Beat - Project X",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 150,
    musicalKey: "D Minor",
    genres: ["Trap", "Plugg"],
    tags: ["kankan", "plugg", "melodic", "slayworld"],
    typeBeat: "Kankan",
    mood: ["Energetic", "Melodic", "Underground"],
    image: "/kankan-px.jpg",
    audioUrl: "/audio/kankan-px.mp3",
    isFree: false,
  },

  // Izaya Tiji Type Beats
  {
    id: "beat-izaya-1",
    title: "Izaya Tiji Type Beat - Bane",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 155,
    musicalKey: "F# Minor",
    genres: ["Trap", "Plugg"],
    tags: ["izaya tiji", "plugg", "melodic", "slayworld"],
    typeBeat: "Izaya Tiji",
    mood: ["Energetic", "Dark", "Melodic"],
    image: "/izaya-bane.jpg",
    audioUrl: "/audio/izaya-bane.mp3",
    isFree: false,
  },

  // Lucki Type Beats
  {
    id: "beat-lucki-1",
    title: "Lucki Type Beat - Freewave 3",
    artist: "FЯEEZY",
    price: "$45.00",
    bpm: 130,
    musicalKey: "G Minor",
    genres: ["Hip Hop", "Alternative"],
    tags: ["lucki", "ambient", "melodic", "chicago"],
    typeBeat: "Lucki",
    mood: ["Chill", "Atmospheric", "Melodic"],
    image: "/lucki-fw3.jpg",
    audioUrl: "/audio/lucki-fw3.mp3",
    isFree: false,
  },

  // Duwap Kaine Type Beats
  {
    id: "beat-duwap-1",
    title: "Duwap Kaine Type Beat - Underdog",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 140,
    musicalKey: "C Minor",
    genres: ["Trap", "Plugg"],
    tags: ["duwap kaine", "plugg", "melodic", "savannah"],
    typeBeat: "Duwap Kaine",
    mood: ["Melodic", "Chill", "Underground"],
    image: "/duwap-underdog.jpg",
    audioUrl: "/audio/duwap-underdog.mp3",
    isFree: false,
  },

  // BabySantana Type Beats
  {
    id: "beat-babysantana-1",
    title: "BabySantana Type Beat - Antisocial",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 160,
    musicalKey: "A Minor",
    genres: ["Trap", "Hyperpop"],
    tags: ["babysantana", "hyperpop", "fast", "energetic"],
    typeBeat: "BabySantana",
    mood: ["Energetic", "Chaotic", "Aggressive"],
    image: "/babysantana-antisocial.jpg",
    audioUrl: "/audio/babysantana-antisocial.mp3",
    isFree: false,
  },

  // SSGKobe Type Beats
  {
    id: "beat-ssgkobe-1",
    title: "SSGKobe Type Beat - KO",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 145,
    musicalKey: "E Minor",
    genres: ["Trap", "Melodic"],
    tags: ["ssgkobe", "melodic", "emotional", "louisiana"],
    typeBeat: "SSGKobe",
    mood: ["Melodic", "Emotional", "Energetic"],
    image: "/ssgkobe-ko.jpg",
    audioUrl: "/audio/ssgkobe-ko.mp3",
    isFree: false,
  },

  // Iayze Type Beats
  {
    id: "beat-iayze-1",
    title: "Iayze Type Beat - Final Fantasy",
    artist: "FЯEEZY",
    price: "$42.00",
    bpm: 150,
    musicalKey: "D Minor",
    genres: ["Trap", "Rage"],
    tags: ["iayze", "rage", "melodic", "texas"],
    typeBeat: "Iayze",
    mood: ["Aggressive", "Melodic", "Energetic"],
    image: "/iayze-ff.jpg",
    audioUrl: "/audio/iayze-ff.mp3",
    isFree: false,
  },

  // Slump6s Type Beats
  {
    id: "beat-slump6s-1",
    title: "Slump6s Type Beat - Dicey",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 155,
    musicalKey: "F Minor",
    genres: ["Trap", "Plugg"],
    tags: ["slump6s", "plugg", "melodic", "florida"],
    typeBeat: "Slump6s",
    mood: ["Melodic", "Energetic", "Underground"],
    image: "/slump6s-dicey.jpg",
    audioUrl: "/audio/slump6s-dicey.mp3",
    isFree: false,
  },

  // Nettspend Type Beats
  {
    id: "beat-nettspend-1",
    title: "Nettspend Type Beat - Think I Like It",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 145,
    musicalKey: "G Minor",
    genres: ["Trap", "Plugg"],
    tags: ["nettspend", "plugg", "melodic", "virginia"],
    typeBeat: "Nettspend",
    mood: ["Melodic", "Chill", "Underground"],
    image: "/nettspend-tili.jpg",
    audioUrl: "/audio/nettspend-tili.mp3",
    isFree: false,
  },

  // Che Type Beats
  {
    id: "beat-che-1",
    title: "Che Type Beat - Starboy",
    artist: "FЯEEZY",
    price: "$38.00",
    bpm: 140,
    musicalKey: "C# Minor",
    genres: ["Trap", "Plugg"],
    tags: ["che", "plugg", "melodic", "underground"],
    typeBeat: "Che",
    mood: ["Melodic", "Atmospheric", "Chill"],
    image: "/che-starboy.jpg",
    audioUrl: "/audio/che-starboy.mp3",
    isFree: false,
  },

  // Generic Beats (No Type Beat)
  {
    id: "beat-generic-1",
    title: "Midnight Drive - Dark R&B Beat",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 140,
    musicalKey: "A Minor",
    genres: ["R&B", "Trap"],
    tags: ["dark rnb", "smooth", "atmospheric"],
    mood: ["Dark", "Smooth", "Atmospheric"],
    image: "/music-producer-studio.png",
    audioUrl: "/audio/midnight-drive.mp3",
    isFree: true,
  },
  {
    id: "beat-generic-2",
    title: "Purple Haze - Melodic Trap",
    artist: "FЯEEZY",
    price: "$25.00",
    bpm: 88,
    musicalKey: "E Minor",
    genres: ["Trap", "Melodic"],
    tags: ["melodic trap", "hard 808", "ambient"],
    mood: ["Chill", "Atmospheric", "Melodic"],
    image: "/abstract-music-waves.png",
    audioUrl: "/audio/purple-haze.mp3",
    isFree: false,
  },
  {
    id: "beat-generic-3",
    title: "Neon Nights - Guitar Beat",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 124,
    musicalKey: "C Major",
    genres: ["Alternative", "Trap"],
    tags: ["guitar", "hyperpop", "energetic"],
    mood: ["Energetic", "Uplifting", "Creative"],
    image: "/neon-guitar.jpg",
    audioUrl: "/audio/neon-nights.mp3",
    isFree: true,
  },
  {
    id: "beat-generic-4",
    title: "West Coast Vibes",
    artist: "FЯEEZY",
    price: "$40.00",
    bpm: 134,
    musicalKey: "G Major",
    genres: ["West Coast", "Hip Hop"],
    tags: ["westcoast", "chill", "smooth"],
    mood: ["Chill", "Smooth", "Happy"],
    image: "/california-sunset.jpg",
    audioUrl: "/audio/west-coast.mp3",
    isFree: false,
  },
  {
    id: "beat-generic-5",
    title: "Rage Mode - Hard Beat",
    artist: "FЯEEZY",
    price: "$30.00",
    bpm: 146,
    musicalKey: "D Minor",
    genres: ["Trap", "Hard"],
    tags: ["rage", "hard", "aggressive"],
    mood: ["Aggressive", "Energetic", "Dark"],
    image: "/dark-experimental-art.jpg",
    audioUrl: "/audio/rage-mode.mp3",
    isFree: false,
  },
  {
    id: "beat-generic-6",
    title: "Soul Searching",
    artist: "FЯEEZY",
    price: "$25.00",
    bpm: 93,
    musicalKey: "F Major",
    genres: ["Hip Hop", "Soul"],
    tags: ["soulful", "sample", "emotional"],
    mood: ["Emotional", "Reflective", "Chill"],
    image: "/urban-city-night.png",
    audioUrl: "/audio/soul-searching.mp3",
    isFree: false,
  },
  {
    id: "beat-generic-7",
    title: "Lo-Fi Chill Beats",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 85,
    musicalKey: "C Major",
    genres: ["Lo-Fi", "Hip Hop"],
    tags: ["chill", "study", "relaxing"],
    mood: ["Chill", "Relaxing", "Happy"],
    image: "/lofi-aesthetic.jpg",
    audioUrl: "/audio/lofi-chill.mp3",
    isFree: true,
  },
  {
    id: "beat-generic-8",
    title: "Boom Bap Classic",
    artist: "FЯEEZY",
    price: "FREE",
    bpm: 90,
    musicalKey: "D Minor",
    genres: ["Boom Bap", "Hip Hop"],
    tags: ["boom bap", "classic", "90s"],
    mood: ["Nostalgic", "Chill", "Confident"],
    image: "/90s-hiphop.jpg",
    audioUrl: "/audio/boom-bap.mp3",
    isFree: true,
  },
  {
    id: "beat-generic-9",
    title: "EDM Banger",
    artist: "FЯEEZY",
    price: "$55.00",
    bpm: 128,
    musicalKey: "A Major",
    genres: ["EDM", "Electronic"],
    tags: ["edm", "festival", "energetic"],
    mood: ["Energetic", "Uplifting", "Party"],
    image: "/edm-festival.png",
    audioUrl: "/audio/edm-banger.mp3",
    isFree: false,
  },
  {
    id: "beat-generic-10",
    title: "Jazz Hop Instrumental",
    artist: "FЯEEZY",
    price: "$32.00",
    bpm: 88,
    musicalKey: "Bb Major",
    genres: ["Jazz", "Hip Hop"],
    tags: ["jazz", "smooth", "sophisticated"],
    typeBeat: "",
    mood: ["Chill", "Smooth", "Sophisticated"],
    image: "/jazz-saxophone.jpg",
    audioUrl: "/audio/jazz-hop.mp3",
    isFree: false,
  },
]
